### ISSUE TITLE
/tpr - command for teleporting to specified mc region coordinates

### ISSUE THREAD

**Issue by Agrrox** [BuildTheEarth/terraplusplus#25] opened 2021-03-04 20:02 UTC
I would like to see command that teleports you to specified minecraft region for example: 
`/tpr 3200,-6500` or `/tpregion 3200,-6500.`

**Describe alternatives you've considered**
Maybe make this as t++ addon that contains extra utility commands?

**Comment by SmylerMC** [comment] 2021-03-05 06:55
Duplicate of #3
My opinion of the matter hasn't changed, this should be implemented in CubicChunks instead.
It is also just a matter of multiplying by 256 for 3dr or 512 for 2dr and mca, so you can do it pretty easily with `/tp`.

**Comment by DaMatrix** [comment] 2021-03-05 10:34
this is definitely beyond of the scope of either terra++ or cubic chunks.

**Closed by DaMatrix** 2021-03-05 10:34 UTC
Labels: Duplicate, Feature
